### ISSUE TITLE
authorization integration

### ISSUE THREAD

**Issue by gagalago** [AaronLasseigne/active_interaction#494] opened 2021-02-10 13:55 UTC
Authorization is for me answering the question "can I perform the action?".
To be able to reflect that I was thinking of doing the following in the controller thanks to [pundit](https://github.com/varvet/pundit):
```ruby
def update
  inputs = { account: find_account! }.reverse_merge(params[:account])
  interaction = UpdateAccount.new(inputs)

  authorize interaction
  outcome = interaction.run

  if outcome.valid?
    redirect_to(outcome.result)
  else
    @account = outcome
    render(:edit)
  end
end
```
to be able to do that I need that [`Runnable#run` change his visibility to be public](https://github.com/AaronLasseigne/active_interaction/blob/v4.0.0/lib/active_interaction/concerns/runnable.rb#L53).

Do you feel that it's a good way of achieving my need and that I can propose a pull request with that change? Or you have a better way of doing authorization with interaction?

**Comment by spencersteiner** [comment] 2021-02-10 22:03
Hey @gagalago! I’m not a maintainer of this project, but I thought I’d chime in on some approaches for solving this with pundit (I think authorization is out of scope for ActiveInteraction, but fortunately pundit is flexible and can be integrated nicely)

Permissions can be authorized at the controller level, or inside the interaction objects themselves (there are varying opinions on where this type of authorization logic belongs) with options that pundit gives you out of the box. Since you’re handling that at the controller level currently I’ll give you two examples:

#### Example One
Here I've just refactored your sample code slightly -- defining the `@account` variable immediately and calling `authorize` directly on the find_account! method (which will presumably return the account that needs to be updated/authorized -- so the account is loaded and authorized all in the first line).
``` ruby
def update
  @account = authorize find_account!
  inputs = { account: @account }.reverse_merge(params[:account])
  outcome = UpdateAccount.run(inputs)

  if outcome.valid?
    redirect_to(outcome.result)
  else
    @account = outcome
    render(:edit)
  end
end
```

#### Example Two

An alternative way to solve the issue is to utilize the `policy_class` option give to us by pundit. You could keep your existing sample code, but modify the `authorize interaction` line to use the AccountPolicy explicitly: 
`authorize interaction, policy_class: AccountPolicy` This solution is less ideal in my opinion, as it will actually require more lines of code and also be less readable. But it would work if that's what you wanted to do!

In addition you can pass the user object into the interaction and call `Pundit.authorize` while skipping authorization logic in the controller entirely. This would be ideal if it's common for you to execute these interactions outside of a controller context

**Comment by gagalago** [comment] 2021-02-11 09:05
I have done your example one until now. But I feel that writing it in that way is more answering "can I access the resource(s) needed for the action?" but it's not because you can access resources needed that you can perform the interaction. It's like exposing inside the controller the internals of the interaction and so the purpose of interaction to encapsulate his own logic just break :disappointed:. So my goal is to authorize the interaction and not resources used by it.

Maybe doing the following is then a better fit (except that I create twice the interaction):
```ruby
def update
  inputs = params[:account]
  interaction = UpdateAccount.new(inputs)

  authorize interaction
  outcome = UpdateAccount.run(interaction.inputs)

  if outcome.valid?
    redirect_to(outcome.result)
  else
    @account = outcome
    render(:edit)
  end
end
```

I discover that I similar discussion already appear in https://github.com/AaronLasseigne/active_interaction/issues/220

So another option provided by @tfausak is to use this base interaction class:
```ruby
class ApplicationInteraction < ActiveInteraction::Base
  public :run, :run!
end
```
But as said, we now need to be careful to not run twice the same interaction.

So do you think that I can provide a pull request that change the visibility of `#run` and add an option that will prevent the interaction to run twice?

**Comment by mihaic195** [comment] 2021-02-11 09:20
I agree with @gagalago that given the examples of @spencersteiner , the controller needs to know the resource as well as the interaction, whereas deciding if I'm authorized to perform the interaction and then running the interaction, I think is a better approach without having to know anything about the resource inside the controller, only the result of the interaction.

Also, doing the authorization inside the interaction can be a drawback in the case where the interaction is called by some worker or service object.

Maybe @AaronLasseigne can provide some tips or suggestions?

**Comment by AaronLasseigne** [comment] 2021-02-12 03:28
I think using both `.new` and `.run` is your best bet. It's not ideal that you have to use the interaction twice but it works and doesn't require thinking through all of the implications of making those instance methods public.

**Closed by AaronLasseigne** 2021-02-12 03:28 UTC
Labels: question
